image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2


build_openvpn:
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY:openvpn-latest ./ovpn-setup

build_wireguard:
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY:wireguard-latest ./wireguard-setup

push_openvpn:
  stage: push
  script:
    - docker push $DOCKER_REGISTRY:openvpn-latest

push_wireguard:
  stage: push
  script:
    - docker push $DOCKER_REGISTRY:wireguard-latest

